

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PROJECTBDS.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

using System.Data.Entity.Core.Objects;
using System.Linq;


public partial class LandSoftEntities : DbContext
{
    public LandSoftEntities()
        : base("name=LandSoftEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }

    public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }

    public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }

    public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }

    public virtual DbSet<tblCategory> tblCategory { get; set; }

    public virtual DbSet<tblCompany> tblCompany { get; set; }

    public virtual DbSet<tblConfig> tblConfig { get; set; }

    public virtual DbSet<tblCustomer> tblCustomer { get; set; }

    public virtual DbSet<tblDictionary> tblDictionary { get; set; }

    public virtual DbSet<tblDistrict> tblDistrict { get; set; }

    public virtual DbSet<tblImage> tblImage { get; set; }

    public virtual DbSet<tblLand> tblLand { get; set; }

    public virtual DbSet<tblNews> tblNews { get; set; }

    public virtual DbSet<tblProject> tblProject { get; set; }

    public virtual DbSet<tblProjectDetail> tblProjectDetail { get; set; }

    public virtual DbSet<tblProvince> tblProvince { get; set; }

    public virtual DbSet<tblWard> tblWard { get; set; }

    public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }

    public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }

    public virtual DbSet<tblContact> tblContact { get; set; }


    [DbFunction("LandSoftEntities", "SplitString")]
    public virtual IQueryable<SplitString_Result> SplitString(string @string, string delimiter)
    {

        var stringParameter = @string != null ?
            new ObjectParameter("String", @string) :
            new ObjectParameter("String", typeof(string));


        var delimiterParameter = delimiter != null ?
            new ObjectParameter("Delimiter", delimiter) :
            new ObjectParameter("Delimiter", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<SplitString_Result>("[LandSoftEntities].[SplitString](@String, @Delimiter)", stringParameter, delimiterParameter);
    }

}

}

