
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PROJECTBDS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tblConfig
{

    public int Id { get; set; }

    public string Name { get; set; }

    public string Address { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public string Hotline { get; set; }

    public string Fax { get; set; }

    public string Map { get; set; }

    public string LicenseNumber { get; set; }

    public string IssuedBy { get; set; }

    public string IssuedPlace { get; set; }

    public string Skype { get; set; }

    public string Facebook { get; set; }

    public string GooglePlus { get; set; }

    public string Youtube { get; set; }

    public string MetaTitle { get; set; }

    public string MetaDesc { get; set; }

    public string MetaKeyword { get; set; }

    public string Logo { get; set; }

    public Nullable<System.DateTime> IssuedDate { get; set; }

}

}
