//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROJECTBDS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCustomer()
        {
            this.tblLand = new HashSet<tblLand>();
        }
    
        public int Id { get; set; }
        public string FullName { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Image { get; set; }
        public Nullable<int> ProvinceId { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public Nullable<int> WardId { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public bool Sex { get; set; }
        public string Skype { get; set; }
        public string Email { get; set; }
    
        public virtual tblCustomer tblCustomer1 { get; set; }
        public virtual tblCustomer tblCustomer2 { get; set; }
        public virtual tblDistrict tblDistrict { get; set; }
        public virtual tblProvince tblProvince { get; set; }
        public virtual tblWard tblWard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLand> tblLand { get; set; }
    }
}
