
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PROJECTBDS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tblCompany
{

    public int Id { get; set; }

    public string Title { get; set; }

    public string Contents { get; set; }

    public string MetaDesc { get; set; }

    public string MetaTitle { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public Nullable<int> Orders { get; set; }

}

}
