//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROJECTBDS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLand
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Desc { get; set; }
        public string Content { get; set; }
        public string MetaTitle { get; set; }
        public string MetaDesc { get; set; }
        public string Image { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string Code { get; set; }
        public string Area { get; set; }
        public string Road { get; set; }
        public Nullable<int> DirectionId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<int> ProvinceId { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public Nullable<int> WardId { get; set; }
        public Nullable<int> RuleId { get; set; }
        public string Address { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Avatar { get; set; }
        public string Map { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string xmap { get; set; }
        public string ymap { get; set; }
    
        public virtual tblDictionary tblDictionary { get; set; }
        public virtual tblDictionary tblDictionary1 { get; set; }
        public virtual tblDictionary tblDictionary2 { get; set; }
        public virtual tblDictionary tblDictionary3 { get; set; }
        public virtual tblDictionary tblDictionary4 { get; set; }
        public virtual tblDistrict tblDistrict { get; set; }
        public virtual tblProject tblProject { get; set; }
        public virtual tblProvince tblProvince { get; set; }
        public virtual tblWard tblWard { get; set; }
    }
}
