
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PROJECTBDS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tblNews
{

    public int Id { get; set; }

    public string Title { get; set; }

    public string Contents { get; set; }

    public string Desc { get; set; }

    public string MetaTitle { get; set; }

    public string MetaDesc { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public string Image { get; set; }

    public Nullable<int> CateId { get; set; }

    public Nullable<int> ProvinceId { get; set; }

    public Nullable<System.DateTime> Date { get; set; }

    public Nullable<int> TimeId { get; set; }

    public string Address { get; set; }

    public Nullable<int> DistrictId { get; set; }

    public string Map { get; set; }



    public virtual tblDictionary tblDictionary { get; set; }

    public virtual tblDictionary tblDictionary1 { get; set; }

    public virtual tblProvince tblProvince { get; set; }

    public virtual tblDistrict tblDistrict { get; set; }

}

}
