
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PROJECTBDS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tblProject
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblProject()
    {

        this.tblImage = new HashSet<tblImage>();

        this.tblLand = new HashSet<tblLand>();

        this.tblProjectDetail = new HashSet<tblProjectDetail>();

    }


    public int Id { get; set; }

    public string Title { get; set; }

    public string Desc { get; set; }

    public string Image { get; set; }

    public string MetaTitle { get; set; }

    public string MetaDesc { get; set; }

    public string Content { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public bool Delete { get; set; }

    public Nullable<int> ProvinceId { get; set; }

    public Nullable<int> DistrictId { get; set; }

    public string Price { get; set; }

    public string Logo { get; set; }



    public virtual tblDistrict tblDistrict { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblImage> tblImage { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblLand> tblLand { get; set; }

    public virtual tblProvince tblProvince { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblProjectDetail> tblProjectDetail { get; set; }

}

}
